"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import type { Lead } from "@/lib/leads/types";

type Row = Record<string, string | number | undefined> & { __row: number; __duplicateAction?: "skip" | "merge" | "import"; __duplicateOfId?: string };
const fields = ["customer_name", "phone", "email", "lead_source", "brand", "vehicle_model", "registration_or_stock_number", "county", "assigned_salesperson", "lead_status", "date_time_received", "notes"] as const;
const titles: Record<typeof fields[number], string> = { customer_name: "Customer name", phone: "Phone", email: "Email", lead_source: "Lead source", brand: "Brand", vehicle_model: "Vehicle/model", registration_or_stock_number: "Registration or stock", county: "County", assigned_salesperson: "Assigned salesperson", lead_status: "Lead status", date_time_received: "Date/time received", notes: "Notes" };
const parseCsv = (text: string) => {
  const values: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false;
  for (let i = 0; i < text.length; i += 1) { const char = text[i]; if (char === '"') { if (quoted && text[i + 1] === '"') { cell += char; i += 1; } else quoted = !quoted; } else if (char === "," && !quoted) { row.push(cell.trim()); cell = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[i + 1] === "\n") i += 1; row.push(cell.trim()); if (row.some(Boolean)) values.push(row); row = []; cell = ""; } else cell += char; }
  row.push(cell.trim()); if (row.some(Boolean)) values.push(row); return values;
};
const guessedField = (header: string) => fields.find((field) => field === header.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "")) ?? "";
const phoneKey = (value?: string | null) => (value || "").replace(/[^0-9]/g, "").replace(/^0/, "353");

export function LeadCsvImport({ leads, onComplete }: { leads: Lead[]; onComplete: () => void }) {
  const [open, setOpen] = useState(false); const [fileName, setFileName] = useState(""); const [headers, setHeaders] = useState<string[]>([]); const [rawRows, setRawRows] = useState<string[][]>([]); const [mapping, setMapping] = useState<Record<string, string>>({}); const [duplicateActions, setDuplicateActions] = useState<Record<number, "skip" | "merge" | "import">>({}); const [notice, setNotice] = useState(""); const [sending, setSending] = useState(false);
  const rows = useMemo<Row[]>(() => rawRows.map((raw, index) => { const item: Row = { __row: index + 2 }; headers.forEach((header, column) => { const field = mapping[header]; if (field) item[field] = raw[column] || ""; }); return item; }), [rawRows, headers, mapping]);
  const existing = useMemo(() => { const matches = new Map<string, string>(); leads.forEach((lead) => { if (lead.email) matches.set(`email:${lead.email.toLowerCase()}`, lead.id); const phone = phoneKey(lead.phone); if (phone) matches.set(`phone:${phone}`, lead.id); }); return matches; }, [leads]);
  const duplicateRows = rows.filter((row) => existing.has(`email:${String(row.email || "").toLowerCase()}`) || existing.has(`phone:${phoneKey(String(row.phone || ""))}`));
  const chooseFile = async (file?: File) => { if (!file) return; if (!file.name.toLowerCase().endsWith(".csv")) { setNotice("Please choose a CSV file."); return; } const parsed = parseCsv(await file.text()); if (parsed.length < 2) { setNotice("The CSV needs a header row and at least one lead."); return; } const nextHeaders = parsed[0]; setHeaders(nextHeaders); setRawRows(parsed.slice(1)); setMapping(Object.fromEntries(nextHeaders.map((header) => [header, guessedField(header)]))); setFileName(file.name); setNotice(""); };
  const actionFor = (row: Row) => duplicateActions[row.__row] || "skip";
  const submit = async () => { if (!rows.length) return; setSending(true); const payload = rows.map((row) => { const match = existing.get(`email:${String(row.email || "").toLowerCase()}`) || existing.get(`phone:${phoneKey(String(row.phone || ""))}`); return { ...row, __duplicateAction: match ? actionFor(row) : "import", __duplicateOfId: match }; }); const response = await fetch("/api/leads/import", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ fileName, rows: payload }) }); const result = await response.json() as { error?: string; imported?: number; skipped?: number; merged?: number; errors?: { row: number; reason: string }[] }; setSending(false); if (!response.ok) { setNotice(result.error || "The import could not be completed."); return; } const failures = result.errors?.length ? ` ${result.errors.length} row(s) need attention: ${result.errors.slice(0, 2).map((item) => `row ${item.row}: ${item.reason}`).join("; ")}` : ""; setNotice(`${result.imported} imported, ${result.merged} merged and ${result.skipped} skipped.${failures}${result.errors?.length ? " Resolve the listed rows, then refresh to see imported leads." : ""}`); if (!result.errors?.length) onComplete(); };
  return <><button type="button" className="button" onClick={() => setOpen(true)}>Import CSV</button>{open ? <div className="leads-modal-backdrop" role="presentation"><section className="leads-import-modal" role="dialog" aria-modal="true" aria-label="Import leads from CSV"><div className="leads-drawer-head"><div><p className="eyebrow">CSV lead import</p><h2>Review before importing</h2></div><button className="quiet-button" type="button" onClick={() => setOpen(false)}>Close</button></div><div className="leads-import-content"><div className="import-actions"><label className="button primary">Choose CSV<input className="sr-only" type="file" accept=".csv,text/csv" onChange={(event) => chooseFile(event.target.files?.[0])}/></label><Link className="button" href="/api/leads/template" download>Download template</Link></div>{headers.length ? <><p className="small"><strong>{fileName}</strong> · {rows.length} rows found. Map each uploaded column before importing.</p><div className="import-map">{headers.map((header) => <label key={header}>{header}<select value={mapping[header] || ""} onChange={(event) => setMapping({ ...mapping, [header]: event.target.value })}><option value="">Ignore column</option>{fields.map((field) => <option key={field} value={field}>{titles[field]}</option>)}</select></label>)}</div><div className="import-preview"><table className="data-table"><thead><tr><th>Row</th><th>Customer</th><th>Contact</th><th>Source</th><th>Received</th></tr></thead><tbody>{rows.slice(0, 6).map((row) => <tr key={row.__row}><td>{row.__row}</td><td>{row.customer_name || <span className="import-error">Required</span>}</td><td>{row.email || row.phone || <span className="import-error">No contact</span>}</td><td>{row.lead_source || "Unattributed"}</td><td>{row.date_time_received || "Now"}</td></tr>)}</tbody></table></div>{duplicateRows.length ? <div className="duplicate-review"><strong>{duplicateRows.length} likely duplicate{duplicateRows.length === 1 ? "" : "s"}</strong><p className="small">Matched on email or normalised phone. Select how each should be handled.</p>{duplicateRows.slice(0, 12).map((row) => <label key={row.__row} className="duplicate-row"><span>Row {row.__row}: {row.customer_name || "Unnamed lead"}</span><select value={actionFor(row)} onChange={(event) => setDuplicateActions({ ...duplicateActions, [row.__row]: event.target.value as "skip" | "merge" | "import" })}><option value="skip">Skip</option><option value="merge">Merge into existing lead</option><option value="import">Import as duplicate</option></select></label>)}</div> : null}<button type="button" className="button primary" disabled={sending || !rows.some((row) => row.customer_name)} onClick={submit}>{sending ? "Importing…" : "Import reviewed leads"}</button></> : <p className="empty-state">Choose a CSV to preview its rows, match columns and review possible duplicates.</p>}{notice ? <p className="notice">{notice}</p> : null}</div></section></div> : null}</>;
}
