"use client";

import { useMemo, useState, type ReactNode } from "react";
import { leadStatuses, type Lead, type LeadOption, type LeadStatus, type LeadWorkspaceData } from "@/lib/leads/types";
import { LeadCsvImport } from "./csv-import";

type Props = { initialData: LeadWorkspaceData; loadError?: boolean; costPerLead?: number | null };
type Filters = { search: string; source: string; brand: string; model: string; salesperson: string; status: string; period: string; sort: string };
const money = (value: number) => new Intl.NumberFormat("en-IE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);
const formatDate = (value: string) => new Intl.DateTimeFormat("en-IE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const startOfDay = (date = new Date()) => new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime();
const label = (name: string | null) => name || "Unspecified";
const totalBy = (leads: Lead[], pick: (lead: Lead) => string) => Object.entries(leads.reduce<Record<string, number>>((all, lead) => { const key = pick(lead); all[key] = (all[key] ?? 0) + 1; return all; }, {})).sort((a, b) => b[1] - a[1]);

function BarList({ title, rows }: { title: string; rows: [string, number][] }) { const max = Math.max(...rows.map(([, value]) => value), 1); return <article className="card leads-breakdown"><h2 className="section-title">{title}</h2><div className="bar-list">{rows.length ? rows.slice(0, 5).map(([name, value]) => <div key={name}><div className="bar-top"><span>{name}</span><strong>{value}</strong></div><div className="bar-track"><div className="bar-value" style={{ width: `${(value / max) * 100}%` }}/></div></div>) : <p className="small">No leads match the current view.</p>}</div></article>; }

function Trend({ leads, days }: { leads: Lead[]; days: number }) { const values = Array.from({ length: days }, (_, index) => { const day = startOfDay() - (days - 1 - index) * 86_400_000; return leads.filter((lead) => new Date(lead.occurredAt).getTime() >= day && new Date(lead.occurredAt).getTime() < day + 86_400_000).length; }); const max = Math.max(...values, 1); const points = values.map((value, index) => `${days === 1 ? 0 : (index / (days - 1)) * 100},${46 - value / max * 37}`).join(" "); return <article className="chart"><div className="section-heading"><div><p className="chart-label">{days}-day lead trend</p><p className="chart-total">{values.reduce((sum, value) => sum + value, 0)} leads</p></div></div><div className="chart-canvas">{leads.length ? <svg viewBox="0 0 100 48" preserveAspectRatio="none" className="h-full w-full" aria-label={`${days}-day lead trend`}><path className="chart-fill" d={`M ${points} L 100,48 L 0,48 Z`}/><polyline className="chart-line" points={points} fill="none" strokeWidth="1.25" vectorEffect="non-scaling-stroke"/></svg> : <div className="empty-state">No trend data</div>}</div></article>; }

function Field({ value, onChange, children, label: labelText }: { value: string; onChange: (value: string) => void; children: ReactNode; label: string }) { return <label className="leads-filter"><span>{labelText}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{children}</select></label>; }

export function LeadsWorkspace({ initialData, loadError = false, costPerLead = null }: Props) {
  const [leads, setLeads] = useState(initialData.leads); const [filters, setFilters] = useState<Filters>({ search: "", source: "", brand: "", model: "", salesperson: "", status: "", period: "", sort: "newest" }); const [selectedId, setSelectedId] = useState<string | null>(null); const [showNew, setShowNew] = useState(false); const [notice, setNotice] = useState(loadError ? "Live data is unavailable, so you are viewing clearly marked demo data." : "");
  const filtered = useMemo(() => leads.filter((lead) => { const text = `${lead.customerName} ${lead.email ?? ""} ${lead.phone ?? ""} ${lead.registrationOrStockNumber ?? ""}`.toLowerCase(); const periodFloor = filters.period ? Date.now() - Number(filters.period) * 86_400_000 : 0; return (!filters.search || text.includes(filters.search.toLowerCase())) && (!filters.source || lead.source === filters.source) && (!filters.brand || lead.brand === filters.brand) && (!filters.model || lead.model === filters.model) && (!filters.salesperson || lead.salesperson === filters.salesperson) && (!filters.status || lead.status === filters.status) && (!periodFloor || +new Date(lead.occurredAt) >= periodFloor); }).sort((a, b) => filters.sort === "oldest" ? +new Date(a.occurredAt) - +new Date(b.occurredAt) : filters.sort === "source" ? a.source.localeCompare(b.source) : +new Date(b.occurredAt) - +new Date(a.occurredAt)), [leads, filters]);
  const selected = leads.find((lead) => lead.id === selectedId) ?? null; const now = Date.now(); const today = leads.filter((lead) => +new Date(lead.occurredAt) >= startOfDay()).length; const week = leads.filter((lead) => +new Date(lead.occurredAt) >= now - 7 * 86_400_000).length; const month = leads.filter((lead) => +new Date(lead.occurredAt) >= now - 30 * 86_400_000).length;
  const patchLead = async (id: string, changes: Record<string, unknown>) => { setLeads((current) => current.map((lead) => lead.id === id ? { ...lead, ...(changes as Partial<Lead>) } : lead)); if (initialData.usingDemoData) { setNotice("Demo records are editable for preview only and are not saved."); return; } const response = await fetch(`/api/leads/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(changes) }); if (!response.ok) setNotice("The change could not be saved. Please try again."); };
  const addLead = async (form: FormData) => { const salesperson = String(form.get("salesperson")) || null; const notes = String(form.get("notes")); const created: Lead = { id: `local-${Date.now()}`, occurredAt: String(form.get("occurredAt")) || new Date().toISOString(), source: String(form.get("source") || "Unattributed"), sourceSlug: String(form.get("source") || "unattributed").toLowerCase().replace(/[^a-z]+/g, "-"), customerName: String(form.get("customerName")), email: String(form.get("email")) || null, phone: String(form.get("phone")) || null, brand: String(form.get("brand")) || null, model: String(form.get("model")) || null, registrationOrStockNumber: String(form.get("stock")) || null, county: String(form.get("county")) || null, campaign: null, salesperson, salespersonId: initialData.salespeople.find((person) => person.name === salesperson)?.id ?? null, status: (String(form.get("status")) as LeadStatus) || "New", notes: notes ? [{ id: `note-${Date.now()}`, body: notes, createdAt: new Date().toISOString(), authorName: "You" }] : [], isDuplicate: false, isDemo: initialData.usingDemoData }; setLeads((current) => [created, ...current]); setShowNew(false); setSelectedId(created.id); if (initialData.usingDemoData) { setNotice("Demo record added for preview only and is not saved."); return; } const response = await fetch("/api/leads", { method: "POST", body: JSON.stringify(Object.fromEntries(form)), headers: { "content-type": "application/json" } }); if (!response.ok) setNotice("The lead was added locally but could not be saved. Please try again."); };
  return <>
    <header className="page-header"><div><p className="eyebrow">Leads Hub</p><h1 className="page-title">Every enquiry, clearly accounted for.</h1><p className="page-intro">A daily operating view of lead volume, attribution and follow-up — without sales revenue or vehicle profit.</p></div><div className="leads-header-actions"><LeadCsvImport leads={leads} onComplete={() => window.location.reload()}/><button type="button" className="button primary" onClick={() => setShowNew(true)}>Add lead</button></div></header>
    {notice ? <div className="notice" role="status">{notice}</div> : null}
    {initialData.usingDemoData ? <div className="demo-label">Demo data · fictional dealership enquiries</div> : null}
    <section className="kpi-grid leads-kpis"><article className="card kpi"><p className="kpi-label">Leads today</p><p className="kpi-value">{today}</p><p className="kpi-detail">Newest enquiries first</p></article><article className="card kpi"><p className="kpi-label">Leads this week</p><p className="kpi-value">{week}</p><p className="kpi-detail">Rolling seven days</p></article><article className="card kpi"><p className="kpi-label">Leads this month</p><p className="kpi-value">{month}</p><p className="kpi-detail">Rolling 30 days</p></article><article className="card kpi"><p className="kpi-label">Cost per lead</p><p className="kpi-value">{costPerLead === null ? "—" : money(costPerLead)}</p><p className="kpi-detail">{costPerLead === null ? "No linked marketing spend in the last 30 days" : "30-day linked marketing spend"}</p></article></section>
    <section className="section card section-card"><div className="section-heading"><div><h2 className="section-title">Lead momentum</h2><p className="section-description">Daily, 7-day and 30-day demand trends.</p></div></div><div className="chart-grid"><Trend leads={leads} days={1}/><Trend leads={leads} days={7}/><Trend leads={leads} days={30}/></div></section>
    <section className="section leads-breakdown-grid"><BarList title="Leads by source" rows={totalBy(leads, (lead) => lead.source)}/><BarList title="Leads by brand" rows={totalBy(leads, (lead) => label(lead.brand))}/><BarList title="Leads by vehicle/model" rows={totalBy(leads, (lead) => label(lead.model))}/></section>
    <section className="section card leads-feed"><div className="table-head leads-feed-head"><div><h2 className="section-title">Live lead feed</h2><p className="section-description">Search, filter and open every enquiry in one place.</p></div><span className="pill">{filtered.length} shown</span></div><div className="leads-controls"><label className="leads-search"><span className="sr-only">Search leads</span><input value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} placeholder="Search name, email, phone or stock no."/></label><div className="leads-filters"><Field label="Date" value={filters.period} onChange={(period) => setFilters({ ...filters, period })}><option value="">All time</option><option value="1">Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></Field><Field label="Source" value={filters.source} onChange={(source) => setFilters({ ...filters, source })}><option value="">All sources</option>{initialData.sources.map((item) => <option key={item.id}>{item.name}</option>)}</Field><Field label="Brand" value={filters.brand} onChange={(brand) => setFilters({ ...filters, brand })}><option value="">All brands</option>{initialData.brands.map((item) => <option key={item.id}>{item.name}</option>)}</Field><Field label="Model" value={filters.model} onChange={(model) => setFilters({ ...filters, model })}><option value="">All models</option>{initialData.models.map((item) => <option key={item.id}>{item.name}</option>)}</Field><Field label="Owner" value={filters.salesperson} onChange={(salesperson) => setFilters({ ...filters, salesperson })}><option value="">All salespeople</option>{initialData.salespeople.map((item) => <option key={item.id}>{item.name}</option>)}</Field><Field label="Status" value={filters.status} onChange={(status) => setFilters({ ...filters, status })}><option value="">All statuses</option>{leadStatuses.map((status) => <option key={status}>{status}</option>)}</Field><Field label="Sort" value={filters.sort} onChange={(sort) => setFilters({ ...filters, sort })}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="source">Source</option></Field></div></div>
    {filtered.length ? <div className="table-scroll"><table className="data-table leads-table"><thead><tr><th>Date & time</th><th>Customer</th><th>Source</th><th>Vehicle</th><th>Location</th><th>Owner</th><th>Status</th></tr></thead><tbody>{filtered.map((lead) => <tr key={lead.id} tabIndex={0} onClick={() => setSelectedId(lead.id)} onKeyDown={(event) => event.key === "Enter" && setSelectedId(lead.id)}><td>{formatDate(lead.occurredAt)}</td><td><strong>{lead.customerName}</strong><span className="small">{lead.email ?? lead.phone ?? "No contact detail"}</span></td><td>{lead.source}<span className="small">{lead.campaign ?? "No campaign"}</span></td><td>{label(lead.brand)} · {label(lead.model)}<span className="small">{lead.registrationOrStockNumber ?? "No registration / stock"}</span></td><td>{lead.county ?? "—"}</td><td>{lead.salesperson ?? "Unassigned"}</td><td><span className={`badge status-${lead.status.toLowerCase().replace(/[^a-z]+/g, "-")}`}>{lead.status}</span></td></tr>)}</tbody></table></div> : <div className="empty-state"><div><strong>No leads match these filters</strong><p>Clear or broaden a filter to bring enquiries back into view.</p><button type="button" className="button" onClick={() => setFilters({ search: "", source: "", brand: "", model: "", salesperson: "", status: "", period: "", sort: "newest" })}>Clear filters</button></div></div>}</section>
    {selected ? <LeadDetail lead={selected} salespeople={initialData.salespeople} onClose={() => setSelectedId(null)} onChange={patchLead}/> : null}
    {showNew ? <NewLead sources={initialData.sources} brands={initialData.brands} models={initialData.models} salespeople={initialData.salespeople} onClose={() => setShowNew(false)} onSave={addLead}/> : null}
  </>;
}

function LeadDetail({ lead, salespeople, onClose, onChange }: { lead: Lead; salespeople: LeadOption[]; onClose: () => void; onChange: (id: string, changes: Record<string, unknown>) => void }) { const [note, setNote] = useState(""); return <div className="leads-modal-backdrop" role="presentation" onMouseDown={onClose}><aside className="leads-drawer" role="dialog" aria-modal="true" aria-label="Lead detail" onMouseDown={(event) => event.stopPropagation()}><div className="leads-drawer-head"><div><p className="eyebrow">Lead detail {lead.isDemo ? "· Demo" : ""}</p><h2>{lead.customerName}</h2></div><button className="quiet-button" onClick={onClose}>Close</button></div><div className="leads-drawer-content"><div className="lead-detail-grid"><div><span>Received</span><strong>{formatDate(lead.occurredAt)}</strong></div><div><span>Source</span><strong>{lead.source}</strong></div><div><span>Email</span><strong>{lead.email ?? "—"}</strong></div><div><span>Phone</span><strong>{lead.phone ?? "—"}</strong></div><div><span>Vehicle</span><strong>{label(lead.brand)} · {label(lead.model)}</strong></div><div><span>Registration / stock</span><strong>{lead.registrationOrStockNumber ?? "—"}</strong></div><div><span>County</span><strong>{lead.county ?? "—"}</strong></div><div><span>Campaign</span><strong>{lead.campaign ?? "—"}</strong></div></div><div className="form-grid"><label>Status<select value={lead.status} onChange={(event) => onChange(lead.id, { status: event.target.value })}>{leadStatuses.map((status) => <option key={status}>{status}</option>)}</select></label><label>Assigned salesperson<select value={lead.salesperson ?? ""} onChange={(event) => onChange(lead.id, { salesperson: event.target.value || null, salespersonId: salespeople.find((person) => person.name === event.target.value)?.id ?? null })}><option value="">Unassigned</option>{salespeople.map((person) => <option key={person.id}>{person.name}</option>)}</select></label></div><button type="button" className="button" onClick={() => onChange(lead.id, { status: "Duplicate", isDuplicate: true })}>Mark as duplicate</button><section className="lead-notes"><div className="section-heading"><h3 className="section-title">Notes</h3><span className="small">{lead.notes.length}</span></div>{lead.notes.length ? lead.notes.map((item) => <article key={item.id} className="lead-note"><p>{item.body}</p><span>{item.authorName ?? "Team"} · {formatDate(item.createdAt)}</span></article>) : <p className="small">No notes yet.</p>}<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Add a note for the team"/><button type="button" className="button primary" disabled={!note.trim()} onClick={() => { onChange(lead.id, { notes: [...lead.notes, { id: `note-${Date.now()}`, body: note.trim(), createdAt: new Date().toISOString(), authorName: "You" }] }); setNote(""); }}>Add note</button></section></div></aside></div>; }

function NewLead({ sources, brands, models, salespeople, onClose, onSave }: { sources: LeadOption[]; brands: LeadOption[]; models: LeadOption[]; salespeople: LeadOption[]; onClose: () => void; onSave: (form: FormData) => void }) { return <div className="leads-modal-backdrop" role="presentation"><form className="leads-new-modal" action={onSave}><div className="leads-drawer-head"><div><p className="eyebrow">Manual entry</p><h2>Add a lead</h2></div><button type="button" className="quiet-button" onClick={onClose}>Close</button></div><div className="form-grid"><label>Customer name<input required name="customerName" placeholder="Customer name"/></label><div className="leads-form-two"><label>Email<input name="email" type="email" placeholder="name@example.com"/></label><label>Phone<input name="phone" placeholder="+353"/></label></div><div className="leads-form-two"><label>Lead source<select name="source" defaultValue="Unattributed">{sources.map((source) => <option key={source.id}>{source.name}</option>)}</select></label><label>County<input name="county" placeholder="Carlow"/></label></div><div className="leads-form-two"><label>Brand<select name="brand"><option value="">Select brand</option>{brands.map((brand) => <option key={brand.id}>{brand.name}</option>)}</select></label><label>Vehicle / model<select name="model"><option value="">Select model</option>{models.map((model) => <option key={model.id}>{model.name}</option>)}</select></label></div><div className="leads-form-two"><label>Registration / stock<input name="stock" placeholder="261-CW-0001"/></label><label>Assigned salesperson<select name="salesperson"><option value="">Unassigned</option>{salespeople.map((person) => <option key={person.id}>{person.name}</option>)}</select></label></div><div className="leads-form-two"><label>Lead status<select name="status" defaultValue="New">{leadStatuses.map((status) => <option key={status}>{status}</option>)}</select></label><label>Date/time received<input name="occurredAt" type="datetime-local" defaultValue={new Date().toISOString().slice(0, 16)}/></label></div><label>Notes<textarea name="notes" placeholder="Context for the sales team"/></label></div><div className="leads-modal-actions"><button type="button" className="button" onClick={onClose}>Cancel</button><button className="button primary">Add lead</button></div></form></div>; }
