import { providers } from "@/lib/data-platform/providers";
import { createClient } from "@/lib/supabase/server";
import { IntegrationCard, type CurrentIntegration } from "./integration-card";

type SettingRow = { provider: string; connection_status: string; authentication_type: string; account_identifier: string | null; configuration: { notes?: string } | null; encrypted_credentials: string | null; scheduled_sync_enabled: boolean; sync_frequency: string; last_sync_at: string | null; last_sync_status: string | null; last_tested_at: string | null; test_status: string | null };

export default async function IntegrationsPage() {
  const supabase = await createClient(); const settingsResult = await supabase.from("integration_settings").select("provider,connection_status,authentication_type,account_identifier,configuration,encrypted_credentials,scheduled_sync_enabled,sync_frequency,last_sync_at,last_sync_status,last_tested_at,test_status");
  const settings = new Map(((settingsResult.data ?? []) as SettingRow[]).map((row) => [row.provider, row])); const values = [...settings.values()]; const connectedCount = values.filter((setting) => setting.connection_status === "connected").length; const scheduledCount = values.filter((setting) => setting.scheduled_sync_enabled).length;
  return <><header><p className="eyebrow">Settings / Integrations</p><h1 className="page-title">A calmer way to manage sources.</h1><p className="page-intro">Review configuration, security and sync preferences from one dependable workspace.</p></header>{settingsResult.error ? <div className="notice" role="status">Integration settings could not be refreshed. You can try again shortly.</div> : null}<section className="settings-summary"><article className="card setting-stat"><p>Available sources</p><strong>{providers.length}</strong></article><article className="card setting-stat"><p>Connected</p><strong>{connectedCount}</strong></article><article className="card setting-stat"><p>Schedules enabled</p><strong>{scheduledCount}</strong></article></section><div className="notice" role="note">Foundation mode: settings are stored securely, but controls do not contact third-party services.</div><section className="integration-grid">{providers.map((provider) => { const row = settings.get(provider.id); const current: CurrentIntegration = { connectionStatus: row?.connection_status ?? "not_connected", authenticationType: row?.authentication_type ?? provider.defaultAuthenticationType, accountIdentifier: row?.account_identifier ?? "", notes: row?.configuration?.notes ?? "", hasCredentials: Boolean(row?.encrypted_credentials), scheduledSyncEnabled: row?.scheduled_sync_enabled ?? false, syncFrequency: row?.sync_frequency ?? "daily", lastSyncAt: row?.last_sync_at ?? null, lastSyncStatus: row?.last_sync_status ?? null, lastTestedAt: row?.last_tested_at ?? null, testStatus: row?.test_status ?? null }; return <IntegrationCard key={provider.id} provider={provider} current={current}/>; })}</section></>;
}
