import { providers } from "@/lib/data-platform/providers";
import { createClient } from "@/lib/supabase/server";
import { IntegrationCard, type CurrentIntegration } from "./integration-card";
import { getGa4Connection, type Ga4Connection } from "@/lib/integrations/google-analytics";
import { Ga4ConnectionCard } from "./ga4-connection-card";

type SettingRow = { provider: string; connection_status: string; authentication_type: string; account_identifier: string | null; configuration: { notes?: string } | null; encrypted_credentials: string | null; scheduled_sync_enabled: boolean; sync_frequency: string; last_sync_at: string | null; last_sync_status: string | null; last_tested_at: string | null; test_status: string | null };
type MetaConnection = { connection_status: string; ad_account_id: string | null; scheduled_sync_enabled: boolean; sync_frequency: string; last_sync_at: string | null; last_sync_status: string | null; last_tested_at: string | null; last_test_status: string | null };

export default async function IntegrationsPage({ searchParams }: { searchParams: Promise<{ ga4_status?: string; ga4_message?: string }> }) {
  const supabase = await createClient();
  const [{ data: { user } }, settingsResult, params, metaResult] = await Promise.all([
    supabase.auth.getUser(),
    supabase.from("integration_settings").select("provider,connection_status,authentication_type,account_identifier,configuration,encrypted_credentials,scheduled_sync_enabled,sync_frequency,last_sync_at,last_sync_status,last_tested_at,test_status"),
    searchParams,
    supabase.from("meta_connections").select("connection_status,ad_account_id,scheduled_sync_enabled,sync_frequency,last_sync_at,last_sync_status,last_tested_at,last_test_status").maybeSingle()
  ]);
  let ga4Connection: Ga4Connection | null = null; let ga4Error = false;
  if (user) { try { ga4Connection = await getGa4Connection(user.id); } catch { ga4Error = true; } }
  const settings = new Map(((settingsResult.data ?? []) as SettingRow[]).map((row) => [row.provider, row])); const values = [...settings.values()]; const metaConnection = metaResult.data as MetaConnection | null;
  const connectedCount = values.filter((setting) => setting.provider !== "ga4" && setting.provider !== "meta-ads" && setting.connection_status === "connected").length + (metaConnection?.connection_status === "connected" ? 1 : 0) + (ga4Connection && !ga4Connection.needs_reauth ? 1 : 0);
  const scheduledCount = values.filter((setting) => setting.provider !== "meta-ads" && setting.scheduled_sync_enabled).length + (metaConnection?.scheduled_sync_enabled ? 1 : 0) + (ga4Connection ? 1 : 0);
  return <><header><p className="eyebrow">Settings / Integrations</p><h1 className="page-title">A calmer way to manage sources.</h1><p className="page-intro">Review configuration, security and sync preferences from one dependable workspace.</p></header>{params.ga4_message ? <div className="notice" role={params.ga4_status === "error" ? "alert" : "status"}>{params.ga4_message}</div> : null}{settingsResult.error || ga4Error ? <div className="notice" role="status">Integration settings could not be fully refreshed. You can try again shortly.</div> : null}<section className="settings-summary"><article className="card setting-stat"><p>Available sources</p><strong>{providers.length}</strong></article><article className="card setting-stat"><p>Connected</p><strong>{connectedCount}</strong></article><article className="card setting-stat"><p>Schedules enabled</p><strong>{scheduledCount}</strong></article></section><div className="notice" role="note">Live connections use their provider’s secure OAuth flow. Other sources remain available for staged setup.</div><section className="integration-grid">{providers.map((provider) => { if (provider.id === "ga4") return <Ga4ConnectionCard key={provider.id} connection={ga4Connection}/>; const row = settings.get(provider.id); const current: CurrentIntegration = provider.id === "meta-ads" ? { connectionStatus: metaConnection?.connection_status ?? "not_connected", authenticationType: "oauth", accountIdentifier: metaConnection?.ad_account_id ?? "", notes: "", hasCredentials: Boolean(metaConnection), scheduledSyncEnabled: metaConnection?.scheduled_sync_enabled ?? false, syncFrequency: metaConnection?.sync_frequency ?? "daily", lastSyncAt: metaConnection?.last_sync_at ?? null, lastSyncStatus: metaConnection?.last_sync_status ?? null, lastTestedAt: metaConnection?.last_tested_at ?? null, testStatus: metaConnection?.last_test_status ?? null } : { connectionStatus: row?.connection_status ?? "not_connected", authenticationType: row?.authentication_type ?? provider.defaultAuthenticationType, accountIdentifier: row?.account_identifier ?? "", notes: row?.configuration?.notes ?? "", hasCredentials: Boolean(row?.encrypted_credentials), scheduledSyncEnabled: row?.scheduled_sync_enabled ?? false, syncFrequency: row?.sync_frequency ?? "daily", lastSyncAt: row?.last_sync_at ?? null, lastSyncStatus: row?.last_sync_status ?? null, lastTestedAt: row?.last_tested_at ?? null, testStatus: row?.test_status ?? null }; return <IntegrationCard key={provider.id} provider={provider} current={current}/>; })}</section></>;
}
